### ISSUE TITLE
How to view DB-probeSniffer.db ?

### ISSUE THREAD

**Issue by dranreb38** [xdavidhu/probeSniffer#11]
Hello,
How to view data in DB-probeSniffer.db.
sqlitebrowser ?
Thank

**Comment by xdavidhu** [comment]
Hey,

Yes, you can use the [sqlitebrowser](http://sqlitebrowser.org/) or on linux you can just install sqlite3 with apt and use it from the command line like this:

`sqlite3 DB-probeSniffer.db`
