### ISSUE TITLE
Perpetually Switching Channels Without Any Data

### ISSUE THREAD

**Issue by de6eling** [xdavidhu/probeSniffer#14]
So I was able to get it up but it doesn't seem to find any sort of packets.  I turned debug on and it just keeps switching channels perpetually.  I am using a Raspberry Pi 3 with a TL-WN722N v1.  Any suggestions?

![image](https://user-images.githubusercontent.com/16584348/35112696-08dc37ee-fc3c-11e7-8159-85212d14b901.png)

**Comment by xdavidhu** [comment]
Hey,
The channel switching is perfectly normal.
The problem you are having is probably that you don't have wlan1 in monitor mode.
Try running `sudo airmon-ng start wlan1` or `sudo iwconfig wlan1 mode monitor` to change it to monitor mode and then try running probeSniffer again.

**Comment by de6eling** [comment]
Thanks for the quick response.  That is what I thought, but when it says its running after that command:

![image](https://user-images.githubusercontent.com/16584348/35113742-c81803ba-fc3f-11e7-9b5a-d9a11331589d.png)

I am pretty new to all of this, but is there maybe a difference between it being enabled and it actually running?

**Comment by xdavidhu** [comment]
It's weird that it says that its enabled on "[phy2]10".

I would suggest you to reboot and run airmon-ng again and you will get back the name of the interface where monitor mode is running, and then you can use that for probeSniffer.

**Comment by xdavidhu** [comment]
Closing this issue for now due to inactivity.
