### ISSUE TITLE
wigle.net request

### ISSUE THREAD

**Issue by BustedSec** [xdavidhu/probeSniffer#2]
How hard would it be to run data in the mysql instance through the wigle api to get geoip coords and then pop it on a map along with the AP name?

also - love this - sensepost did something similar with snoopy-ng but they don't maintain the code well.

**Comment by xdavidhu** [comment]
Great idea for 2.0, already wanted to do it but the problem is that there can be a lot of locations/ssid. So imean e.g. for a "tplink" ssid wigle will find millions of locations, so dunno how to deal with that at this point.

btw, im open for any ideas, just email me.

**Comment by thesle3p** [comment]
Why not search by BSSID not ESSID?

**Comment by xdavidhu** [comment]
@thesl3p - Probe requests not contain BSSID's. :/

**Comment by BustedSec** [comment]
They do in wireless N and AC - just not in A\B\G 

http://imgur.com/a/sZFZY

**Comment by BustedSec** [comment]
Check out https://github.com/sensepost/peanuts
