### ISSUE TITLE
Network down

### ISSUE THREAD

**Issue by vincentcox-work** [xdavidhu/probeSniffer#4]
Is it possible to build in a try and catch or something when the network card drops? I get the following error:
```
!] An error occurred. Debug:
Traceback (most recent call last):
  File "./probeSniffer.py", line 341, in main
    sniff(iface=monitor_iface, prn=PacketHandler)
  File "/usr/local/lib/python3.5/dist-packages/scapy/sendrecv.py", line 590, in sniff
    p = s.recv(MTU)
  File "/usr/local/lib/python3.5/dist-packages/scapy/arch/linux.py", line 502, in recv
    pkt, sa_ll = self.ins.recvfrom(x)
OSError: [Errno 100] Network is down
```
If I re-run it, it works again for a minute or 2. So is it possible to implement a loop to retry without exiting the program?

**Comment by vincentcox-work** [comment]
It can be temporary fixed with: `while true; do ./probeSniffer.py wlan0  -d -b; done`, however it is not very clean to say the least 😅

**Comment by xdavidhu** [comment]
I will make a fix, thats a gread idea!

**Comment by xdavidhu** [comment]
Fixed in:
fa11c7d

Could you please try it now if it restarts after a crash?

**Comment by vincentcox-work** [comment]
Thank you very much for taking time to create a new version. I have installed it and I checked it out.
Unfortunately I get the following error:
```
[I] Sniffing started... Please wait for requests to show up...

[!] An error occurred. Debug:
Traceback (most recent call last):
  File "./probeSniffer.py", line 148, in sniffer
    sniff(iface=monitor_iface, prn=PacketHandler)
  File "/usr/local/lib/python3.5/dist-packages/scapy/sendrecv.py", line 574, in sniff
    s = L2socket(type=ETH_P_ALL, *arg, **karg)
  File "/usr/local/lib/python3.5/dist-packages/scapy/arch/linux.py", line 493, in __init__
    _flush_fd(self.ins)
  File "/usr/local/lib/python3.5/dist-packages/scapy/arch/linux.py", line 313, in _flush_fd
    os.read(fd,MTU)
OSError: [Errno 100] Network is down

[!] Restarting in 5 sec... Press CTRL + C to stop.
^C
[I] Stopping...
[I] Results saved to 'DB-probeSniffer.db'

[I] probeSniffer stopped.

```

**Comment by vincentcox-work** [comment]
I might have problems with my python installation, so no need to dig into this issue yet. I keep you posted.

**Comment by xdavidhu** [comment]
This seems like an interface error. Make sure the interface is up, and it is in monitor mode.

So if you have an interface named "wlan0", note that airmon-ng will change it to "wlan0mon".
But I think you know this since it worked for you before :)
