### ISSUE TITLE
High memory usage after hours of use

### ISSUE THREAD

**Issue by solsticedhiver** [xdavidhu/probeSniffer#7]
I just let probeSniffer.py running for a few hours (4 hours I think) and when I return I found out that 3/4(three quarter) of my main memory (8GB) was fully used.

I killed probeSniffer.py (with CTRL-C) and I was able to get that memory back, freeing it.

Is there some memory leak, or is it the expected behavior given that it runs for hours ?

**Comment by xdavidhu** [comment]
Hey!

Thats weird... Thank you for reporting, I will look into it.
Were there a lot of requests/devices when your memory got filled up?

**Comment by solsticedhiver** [comment]
I got a total of 127 logged mac address/ssid during those 4 hours but I modifed the script to log duplicates. So it's not that much I would say. I only got 18 unique mac_address/ssid

Note: I copied the lines 219-221 and pasted them after line 228

If I run the script and run htop I can see the memory increasing from the start of the script

**Comment by xdavidhu** [comment]
Sorry for the late reply but I belive I fixed the memory leak issue in commit b8f8612b9431a42a151edc58285c95a3be6a6acf.

Please try it and see if the issue is fixed for you.
