### ISSUE TITLE
hii i have a problem starting

### ISSUE THREAD

**Issue by bourla77** [xdavidhu/probeSniffer#8]
Traceback (most recent call last):
  File "probeSniffer.py", line 13, in <module>
    import urllib.request as urllib2
ImportError: No module named request

**Comment by xdavidhu** [comment]
Hi, please run this command to install the dependencies and try again.

`python3 -m pip install -r requirements.txt`

**Comment by bourla77** [comment]
didi it
Requirement already satisfied: scapy-python3 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 1))
im using tp-link tl wn722n 
Tal
still doesnt work/
the command is:
 sudo python probeSniffer.py ??

**Comment by Sloth8204** [comment]
Use

sudo python3 probeSniffer.py

**Comment by xdavidhu** [comment]
Yes, how @Sloth8204 said, you should run probeSniffer with `python3`.
